language: node_js
node_js:
  - "7"
  deploy:
  provider: lambda
  function_name: "hapkidoApi"
  region: "ap-southeast-2"
  role: "arn:aws:iam::845320091708:role/lambda_basic_execution"
  runtime: "nodejs6.10"
  handler_name: "handler"
  access_key_id: "AWS ACCESS KEY ID"
  secret_access_key: "AWS SECRET ACCESS KEY"