INSERT INTO family (family_id, name, contact_address_id) VALUES (1, 'Higgins', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (2, 'Millwood', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (3, 'Van Pelt', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (4, 'Hocking', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (5, 'Gouicem', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (6, 'Langford', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (7, 'Williams', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (8, 'Robinson', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (9, 'Alhamidi', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (10, 'Cass', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (11, 'Leavy', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (12, 'Tyrell', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (13, 'Ghafournejad', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (14, 'Cox', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (15, 'Raniga', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (16, 'Olsson', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (17, 'Alemara', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (18, 'O''Carroll', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (19, 'Nguyen', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (20, 'Nallainathan', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (21, 'Lea', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (22, 'Stefancic', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (23, 'Luddington', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (24, 'Ottley', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (25, 'Oreta', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (26, 'Tjahjono', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (27, 'Britten', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (28, 'Wang', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (29, 'Radovic', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (30, 'Tong', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (31, 'Balaji', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (32, 'Devine', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (33, 'Dorahy', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (34, 'Visitor', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (35, 'Omeros', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (36, 'Segers', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (37, 'Rasuli', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (38, 'McGrath', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (39, 'Kannangara', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (40, 'Ferreira', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (41, 'Rutz', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (42, 'Gray', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (43, 'Curtis', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (44, 'Mackenzie ', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (45, 'Higgins', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (46, 'Pedrosa', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (47, 'Marshall ', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (48, 'Keynes', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (49, 'Sultan ', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (50, 'Kowalik', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (51, 'Thomas', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (52, 'Gilbert', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (53, 'Cocks', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (54, 'Croft', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (55, 'Josey', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (56, 'Mills', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (57, 'Timofeeva', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (58, 'Johnston ', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (59, 'Starr', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (60, 'Bae', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (61, 'Aljorani', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (62, 'McFadden ', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (63, 'Gopinath', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (64, 'Gallagher ', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (65, 'Williamson ', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (66, 'Allen', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (67, 'Brown', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (68, 'BBachana Bowa', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (69, 'Bachana Bowa', null);
INSERT INTO family (family_id, name, contact_address_id) VALUES (70, 'Do', null);