-- MySQL Script generated by MySQL Workbench
-- Tue Mar 27 08:23:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema marti097_hapkido-staging
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marti097_hapkido-staging
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marti097_hapkido-staging` DEFAULT CHARACTER SET utf8 ;
USE `marti097_hapkido-staging` ;

-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`class_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`class_type` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`class_type` (
  `class_type_id` INT NOT NULL AUTO_INCREMENT,
  `class_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`class_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`contact` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`contact` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `street_1` VARCHAR(100) NOT NULL,
  `street_2` VARCHAR(100) NULL,
  `postcode` VARCHAR(4) NOT NULL,
  `suburb` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`family` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`family` (
  `family_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `contact_address_id` INT NULL,
  PRIMARY KEY (`family_id`),
  INDEX `fk_family_contact1_idx` (`contact_address_id` ASC),
  CONSTRAINT `fk_family_contact1`
    FOREIGN KEY (`contact_address_id`)
    REFERENCES `marti097_hapkido-staging`.`contact` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`emergency_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`emergency_contact` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`emergency_contact` (
  `emergency_contact_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone_1` VARCHAR(20) NOT NULL,
  `phone_2` VARCHAR(20) NULL,
  PRIMARY KEY (`emergency_contact_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`member` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`member` (
  `hb_id` VARCHAR(6) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `dob` DATETIME NULL,
  `occupation` VARCHAR(100) NULL,
  `is_active` TINYINT NOT NULL,
  `is_kumdo_student` TINYINT NOT NULL,
  `previous_experience` TEXT(400) NULL,
  `injury_illness` TEXT(400) NULL,
  `is_verified` TINYINT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `preferred_class_type_id` INT NOT NULL,
  `family_id` INT NOT NULL,
  `emergency_contact_id` INT NULL,
  PRIMARY KEY (`hb_id`),
  INDEX `fk_member_class_type1_idx` (`preferred_class_type_id` ASC),
  INDEX `fk_member_family1_idx` (`family_id` ASC),
  INDEX `fk_member_emergency_contact1_idx` (`emergency_contact_id` ASC),
  CONSTRAINT `fk_member_class_type1`
    FOREIGN KEY (`preferred_class_type_id`)
    REFERENCES `marti097_hapkido-staging`.`class_type` (`class_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_family1`
    FOREIGN KEY (`family_id`)
    REFERENCES `marti097_hapkido-staging`.`family` (`family_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_emergency_contact1`
    FOREIGN KEY (`emergency_contact_id`)
    REFERENCES `marti097_hapkido-staging`.`emergency_contact` (`emergency_contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'emergency_contact_emergency_contact_id';


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`class` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`class` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `is_grading` TINYINT NOT NULL,
  `date` DATETIME NOT NULL,
  `class_type_id` INT NOT NULL,
  PRIMARY KEY (`class_id`),
  INDEX `fk_class_class_type1_idx` (`class_type_id` ASC),
  CONSTRAINT `fk_class_class_type1`
    FOREIGN KEY (`class_type_id`)
    REFERENCES `marti097_hapkido-staging`.`class_type` (`class_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`member_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`member_class` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`member_class` (
  `hb_id` VARCHAR(6) NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`hb_id`, `class_id`),
  INDEX `fk_member_class_member1_idx` (`hb_id` ASC),
  INDEX `fk_member_class_class1_idx` (`class_id` ASC),
  CONSTRAINT `fk_member_class_member1`
    FOREIGN KEY (`hb_id`)
    REFERENCES `marti097_hapkido-staging`.`member` (`hb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_class_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `marti097_hapkido-staging`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`grade` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`grade` (
  `grade_id` INT NOT NULL,
  `short_name` VARCHAR(2) NULL,
  `long_name` VARCHAR(20) NULL,
  `css_class` VARCHAR(20) NULL,
  PRIMARY KEY (`grade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marti097_hapkido-staging`.`member_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marti097_hapkido-staging`.`member_grade` ;

CREATE TABLE IF NOT EXISTS `marti097_hapkido-staging`.`member_grade` (
  `grade_id` INT NOT NULL,
  `hb_id` VARCHAR(6) NOT NULL,
  `class_id` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`grade_id`, `hb_id`),
  INDEX `fk_member_grade_member1_idx` (`hb_id` ASC),
  INDEX `fk_member_grade_class1_idx` (`class_id` ASC),
  CONSTRAINT `fk_member_grade_grade1`
    FOREIGN KEY (`grade_id`)
    REFERENCES `marti097_hapkido-staging`.`grade` (`grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_grade_member1`
    FOREIGN KEY (`hb_id`)
    REFERENCES `marti097_hapkido-staging`.`member` (`hb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_grade_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `marti097_hapkido-staging`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
